version: '3.7'
services:
  login-service:
    image: login-service-0.0.1-SNAPSHOT
    build: login-service/
    ports:
    - 9762:9762
    depends_on:
    - dbpostgresql
  rfq-service:
    image: rfq-service:0.0.1-SNAPSHOT
    build: rfq-service/
    ports:
    - 9763:9763
    depends_on:
    - dbpostgresql
    environment:
      SPRING_PROFILES_ACTIVE: docker
    environment:
      SPRING_PROFILES_ACTIVE: docker
  gateway-service:
    image: gateway-service:0.0.1-SNAPSHOT
    build: gateway-service/
    ports:
    - 9760:9760
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
    - rfq-service
    - login-service
  dbpostgresql:
    image: postgres
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=root
    - POSTGRES_USER=postgres
    - POSTGRES_DB=insecuredb